config/routes.rb
Rails.application.routes.draw do
  get 'recommendations/view'
  get 'favourites/view'
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    resources :singers
    get 'search/search', to: 'search#search'
    devise_for :users
    root 'albums#index'
    resources :albums do
      collection do
        get 'search', 'artist', 'top_ranked', 'worst_ranked', 'favourite'
      end
      resources :reviews, except: %i[show index]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/singer.rb
class Singer < ApplicationRecord
  has_many :albums, dependent: :destroy
  belongs_to :user
  has_one_attached :image
  serialize :genres, Array
end

app/controllers/singers_controller.rb
class SingersController < ApplicationController
  before_action :set_singer, only: %i[show edit update destroy]
  before_action :authenticate_user!
  before_action :is_admin?, except: %i[index show]
  # GET /singers or /singers.json
  def index
    @singers = Singer.all
  end

  # GET /singers/1 or /singers/1.json
  def show
    @albums = Album.where(singer_id: @singer.id).order('created_at DESC')
    @a = []
    @albums.each do |album|
      @a.push(album.avg_rating(album)) if album.avg_rating(album) > 0
    end
    @avr = @a.inject(0.0) { |sum, el| sum + el } / @a.size
  end

  # GET /singers/new
  def new
    @singer = Singer.new
  end

  # GET /singers/1/edit
  def edit; end

  # POST /singers or /singers.json
  def create
    @singer = Singer.new(singer_params)
    @singer.user_id = current_user.id
    sin = RSpotify::Artist.search(@singer.name).first
    @singer.avatar = RSpotify::Artist.search(@singer.name).first.images.first['url'] if @singer.name != 'Kanye West'
    @singer.avatar = 'Снимок экрана от 2022-12-14 17-16-05.png' if @singer.name == 'Kanye West'
    @singer.popularity = RSpotify::Artist.search(@singer.name).first.popularity
    @singer.genres = RSpotify::Artist.search(@singer.name).first.genres
    playlist = RSpotify::Playlist.search("This is #{@singer.name}").first
    @singer.thisis = "https://open.spotify.com/embed/playlist/#{playlist.id}?utm_source=generator"
    @singer.mostpop = "https://open.spotify.com/embed/track/#{sin.top_tracks(:US).first.id}?utm_source=generator"
    respond_to do |format|
      if @singer.save
        format.html { redirect_to singer_url(@singer), notice: (t 'singer_create') }
        format.json { render :show, status: :created, location: @singer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @singer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /singers/1 or /singers/1.json
  def update
    respond_to do |format|
      if @singer.update(singer_params)
        format.html { redirect_to singer_url(@singer), notice: (t 'singer_update') }
        format.json { render :show, status: :ok, location: @singer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @singer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /singers/1 or /singers/1.json
  def destroy
    @singer.destroy

    respond_to do |format|
      format.html { redirect_to singers_url, notice: (t 'singer_destroy') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_singer
    @singer = Singer.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def singer_params
    params.require(:singer).permit(:name, :born, :biography, :genres, :inst, :avatar)
  end
end

app/helpers/singers_helper.rb
module SingersHelper
end

app/views/singers/_form.html.erb
<%= form_with(model: singer) do |form| %>
  <% if singer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(singer.errors.count, "error") %> prohibited this singer from being saved:</h2>

      <ul>
        <% singer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="wrapper">
    <form action="#">
        <div class="h5 font-weight-bold mb-3"><%= form.label :name%></div>
        <div class="form-group d-flex align-items-center">
          <%= form.text_field :name, class: "form-control" %>
        </div>    
          <%= form.submit (t "create_singer"), class: "btn btn-primary mb-3"%>                    
    </form>
  </div>
<% end %>

app/views/singers/_singer.html.erb
<div id="<%= dom_id singer %>">
  <p>
    <strong>Name:</strong>
    <%= singer.name %>
  </p>


</div>

app/views/singers/edit.html.erb
<h1 style="color:white;position: relative;left: 35%;"><%= t "editing_singer" %></h1>

<%= render "form", singer: @singer %>

<br>

<div>
  <%= link_to (t "showw"), @singer %> |
  <%= link_to (t "backk"), singers_path %>
</div>

app/views/singers/index.html.erb
<style>
.nice1{
  font-weight: bold;
}

</style>
<%if !user_signed_in? %>
  <div class="jumbotron">
    <h1>Самый лучший сайт на свете</h1>
    <p>Чтобы пользоваться этим сайтом, нужно войти в свой аккаунт или зарегистрироваться</p>
    <p><%= link_to "Войти", new_user_registration_path, class: "btn btn-primary btn-lg"%></p>
  </div>
<%end%>
<h1 style="color:white"><%= t 'current_artists'%></h1>
<div class="row">
  <% @singers.order('name ASC').each do |singer|%>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail", id="bord">
        <% if singer.name == "Kanye West" %>
          <div class="l", id="bard">
            <%= link_to (image_tag singer.avatar,style:"width:250px; height:250px", class: 'image'), singer %>
          </div>
        <% else %>
          <div>
            <%= link_to (image_tag singer.avatar,style:"width:250px; height:250px", class: 'image'), singer %>
          </div>
        <%end%>
        <div class="nice1">
          <%= link_to (singer.name), singer, style: 'color:#000000'%>
        </div>
      </div>
    </div>
  <%end%>
</div>

app/views/singers/new.html.erb
<h1 style="color:white;position: relative;left: 35%;"><%= t "news" %></h1>
<%= render "form", singer: @singer %>

<br>

app/views/singers/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag @singer.avatar, style:"width:400px; height:400px; margin-bottom: 30px" %> 
        <iframe style="border-radius:12px" src=<%= @singer.thisis %> width="115%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe>

      </div>
      <div class="col-md-7 col-md-offset-1">
        <div class="table-responsive">
          <table class="table">
            <h1><%= link_to (@singer.name), @singer, style: 'color:#000000' %></h1>
            <tbody>
              <tr>
                <td><strong><%= t 'most_popular' %></strong></td>
                <td><iframe style="border-radius:12px" src=<%= @singer.mostpop %> width="100%" height="100" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe></td>
              </tr>
              <tr>
                <td><strong><%= t 'popularity' %></strong></td>
                <td><%= "#{@singer.popularity}%" %></td>
              </tr>  
              <tr>
                <td><strong><%= t 'genres' %></strong></td>
                <td><% (@singer.genres).each do |genre|%>
                  <%=genre%> 
                <% end %>
                </td>
              </tr> 
            </tbody>
          </table>
          <h1><strong><%= t 'average_rating'%></strong></h1>
          <% if @a.length == 0 %>
            <p><%= t 'no_reviews'%></p>
          <% elsif  @avr >= 7.5%>
            <div class="green">
              <h2><%= @avr %></h2>
            </div>
          <% elsif  @avr < 7.5 and  @avr >= 4.5%>
            <div class="yellow">
              <h2><%=  @avr %></h2>
            </div>
          <% elsif  @avr < 4.5%>
            <div class="red">
              <h2><%=  @avr %></h2>
            </div>
          <%end%>
        </div>
      </div>
    </div>

      <h1><%= t "singer_albums",  singer: @singer.name %></h1>
      <% @albums.each do |album| %>
        <div class="col-sm-6 col-md-3">
          <%= link_to (image_tag album.cover, style:"width:250px; height:250px", class: 'image'), album %>
          <div class="nice1">
            <%= link_to (album.title), album, style: 'color:#000000'%>
          </div>
        </div>
      <% end %>
  </div>
  <div>
  <% if current_user.admin? %>
    <%= link_to (t "editt"), edit_singer_path(@singer) %> |
    <%= link_to (t "backk"), singers_path %>
    <%= button_to (t "destroyy"), @singer, method: :delete %>
  <% else %>
    <%= link_to (t "backk"), singers_path %>
  <% end %>
</div>
</div>