config/routes.rb
Rails.application.routes.draw do
  get 'recommendations/view'
  get 'favourites/view'
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    resources :singers
    get 'search/search', to: 'search#search'
    devise_for :users
    root 'albums#index'
    resources :albums do
      collection do
        get 'search', 'artist', 'top_ranked', 'worst_ranked', 'favourite'
      end
      resources :reviews, except: %i[show index]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/album.rb
class Album < ApplicationRecord
  searchkick
  has_one_attached :image
  belongs_to :user
  has_many :reviews, dependent: :destroy
  belongs_to :singer
  def avg_rating(album)
    a = Review.where(album_id: album.id).average(:rating)
    return a = 0.0 if a.nil?

    a.round(2)
  end
end

app/controllers/albums_controller.rb
require 'rspotify'
class AlbumsController < ApplicationController
  before_action :set_album, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: [:index]
  before_action :is_admin?, except: %i[index show top_ranked worst_ranked favourite]

  def top_ranked
    @albums = Album.all
    @ar = []
    @albums.each do |album|
      ax = []
      ax.push(album, album.avg_rating(album))
      @ar.push(ax) if album.avg_rating(album) > 0.0
    end
    @ar = @ar.sort_by { |a| -a[1] }
  end

  def worst_ranked
    @albums = Album.all
    @ar = []
    @albums.each do |album|
      ax = []
      ax.push(album, album.avg_rating(album))
      @ar.push(ax) if album.avg_rating(album) > 0.0
    end
    @ar = @ar.sort_by { |a| a[1] }
  end

  def index
    @albums = Album.all.order('created_at DESC')
  end

  # GET /albums/1 or /albums/1.json
  def show
    @reviews = Review.where(album_id: @album.id).order('created_at DESC')
    @avg_review = if @reviews.length == 0
                    0
                  else
                    @reviews.average(:rating).round(2)
                  end
    @favourite_exists = Favourite.where(album: @album, user: current_user) == [] ? false : true
  end

  # GET /albums/new
  def new
    @album = current_user.albums.build
  end

  # GET /albums/1/edit
  def edit; end

  # POST /albums or /albums.json
  def create
    @album = current_user.albums.build(album_params)
    if Singer.find_by(name: @album.artist)
      @singer = Singer.find_by(name: @album.artist)
      @album.singer_id = @singer.id
      @album.label = RSpotify::Album.search(@album.title).first.label
      @album.release_date = RSpotify::Album.search(@album.title).first.release_date
      @album.total_tracks = RSpotify::Album.search(@album.title).first.total_tracks
      @album.popularity = RSpotify::Album.search(@album.title).first.popularity
      @album.cover = RSpotify::Album.search(@album.title).first.images.first['url']
      @album.link = "https://open.spotify.com/embed/album/#{RSpotify::Album.search(@album.title).first.id}?utm_source=generator"
      respond_to do |format|
        if @album.save
          format.html { redirect_to album_url(@album), notice: (t 'album_create') }
          format.json { render :show, status: :created, location: @album }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @album.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path, notice: (t 'album_error')
    end
  end

  # PATCH/PUT /albums/1 or /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to album_url(@album), notice: (t 'album_update') }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1 or /albums/1.json
  def destroy
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url, notice: (t 'album_destroy') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_album
    @album = Album.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def album_params
    params.require(:album).permit(:title, :artist, :cover)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_album.html.erb
<div id="<%= dom_id album %>">
  <p>
    <strong>Title:</strong>
    <%= album.title %>
  </p>

  <p>
    <strong>Artist:</strong>
    <%= album.artist %>
  </p>


</div>

app/views/albums/_form.html.erb
<%= form_with(model: album) do |form| %>
  <% if album.errors.any? %>
    <div style="color: red" class>
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
        <% album.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="wrapper">
    <form action="#">
          <div class="h5 font-weight-bold mb-3"><%= form.label :artist%></div>
          <div class="form-group d-flex align-items-center">
            <%= form.text_field :artist, class: "form-control" %>
          </div>
          <div class="h5 font-weight-bold mb-3"><%= form.label :title %></div>
        <div class="form-group d-flex align-items-center">
          <%= form.text_field :title, class: "form-control" %>
        </div>         
          <%= form.submit (t "create_album"), class: "btn btn-primary mb-3"%>                    
    </form>
  </div>

<% end %>

app/views/albums/edit.html.erb
<h1 style="color:white;position: relative;left: 35%;"><%= t "editing_album" %></h1>
<%= render "form", album: @album %>

<br>

<div>
  <%= link_to (t "show"), @album %> |
  <%= link_to (t "back"), albums_path %>
</div>

app/views/albums/favourite.html.erb
<h1 style="color:white"><%= t "favourite" %></h1>
<div class="row">
  <% current_user.favourites.each do |favourite| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail", id="bord">
        <%= link_to (image_tag favourite.album.cover,style:"width:250px; height:250px", class: 'image'), favourite.album %>
        <div class="nice1">
          <%= link_to (favourite.album.title), favourite.album, style: 'color:#000000'%>
        </div>
        <div>
          <%= link_to (favourite.album.artist), favourite.album, style: 'color:#000000'%>
        </div>
      </div>
    </div>
  <%end%>
</div>

app/views/albums/index.html.erb
<%if !user_signed_in? %>
  <div class="jumbotron">
    <h1><%= t "the_best"%></h1>
    <p><%= t "need" %></p>
    <p><%= link_to (t "log_in"), new_user_registration_path, class: "btn btn-primary btn-lg"%></p>
  </div>
<%end%>
<h1 style="color:white"><b><%= t 'current_albums'%></b></h1>
<div class="row">
  <% @albums.each do |album|%>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail containers", id="bord">
          <%= link_to ( image_tag album.cover,style:"width:250px; height:250px", class: 'image'), album %>
          <div class="middle">
            <div class="text">
              <% if album.avg_rating(album) > 0%>
                <span class="glyphicon glyphicon-star-empty"></span>
                <%= album.avg_rating(album) %>
              <% else%>
                <p>No ratings</p>
              <% end %>
            </div>
          </div>
        <div class="nice1">
          <%= link_to (album.title), album, style: 'color:#000000'%>
        </div>
        <div>
          <%= link_to (album.artist), singer_path(album.singer_id) , style: 'color:#000000'%>
        </div>
      </div>
    </div>
  <%end%>
</div>
<%= link_to 'EN', root_path(locale: :en), class: "navbar-brand"%>
<%= link_to 'RU', root_path(locale: :ru), class: "navbar-brand"%>

app/views/albums/new.html.erb
<h1 style="color:white;position: relative;left: 35%;"><%= t "new" %></h1>
<%= render "form", album: @album %>

<br>

app/views/albums/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag @album.cover, style:"width:400px; height:400px; margin-bottom: 30px" %>
        <iframe style="border-radius:12px" 
          src=<%= @album.link %> width="115%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture">
        </iframe>
      </div>
      
      <div class="col-md-7 col-md-offset-1">
        <div class="table-responsive">
          <table class="table">
            <div class="nice1">
              <h1><%= link_to (@album.title), @album, style: 'color:#000000' %></h1>
              <h3><%= link_to (@album.artist), singer_path(@album.singer_id), style: 'color:#000000' %></h3>
            </div>
            <tbody>
              <tr>
                <td><strong><%= t "label" %></strong></td>
                <td><%= @album.label %></td>
              </tr>
              <tr>
                <td><strong><%= t "released" %></strong></td>
                <td><%= @album.release_date %></td>
              </tr>
              <tr>
                <td><strong><%= t "total_tracks" %></strong></td>
                <td><%= @album.total_tracks %></td>
              </tr>
              <tr>
                <td><strong><%= t "album_popularity" %></strong></td>
                <td><%= "#{@album.popularity}%" %></td>
              </tr>
            </tbody>
          </table>
          <%= link_to favourite_text, favourites_view_path(album: @album), class:"btn btn-danger"%>
          <h2><%= t "Average_Rating" %></h2>
          <% if @reviews.length == 0 %>
            <p><%= t "There_is_no_reviews_yet" %></p>
          <% elsif  @avg_review >= 7.5%>
            <div class="green">
              <h2><%= @avg_review %></h2>
            </div>
          <% elsif  @avg_review < 7.5 and  @avg_review >= 4.5%>
            <div class="yellow">
              <h2><%=  @avg_review %></h2>
            </div>
          <% elsif  @avg_review < 4.5%>
            <div class="red">
              <h2><%=  @avg_review %></h2>
            </div>
          <%end%>
          <h1><%= t "reviews"%></h1>
  <%= link_to (t "write_review"), new_album_review_path(@album), class:"btn btn-danger"%>

  <% if @reviews.blank?%>
      <h3><%= t "no_reviews"%></h3>
  <% else %>
      <em><%= @reviews.length%> <%= t "reviewws"%></em>
      <% @reviews.each do |review| %>
         <div class="reviews">
            <em><%= review.user.email %></em>
            <% review.rating.to_i.times do  %>
              <span class="glyphicon glyphicon-star-empty"></span>
            <% end %>
            <% if current_user.admin? %>
              <div class="rights"><%= button_to (t "delete_review"), album_review_path(@album, review), method: :delete %></div>
            <% end %>
            <b><%= review.rating %> </b>
            <p><%= review.comment%></p>
          </div>
      <% end %>
  <% end %>
        </div>
      </div>
    </div>
  </div>
  <div>
  <% if current_user.admin? %>
    <%= link_to (t "back"), albums_path %>
    <%= button_to (t "destroy"), @album, method: :delete %>
  <% else %>
  <%= link_to (t "back"), albums_path %>
  <% end %>
</div>

</div>

app/views/albums/top_ranked.html.erb
<h1>Top 5 Best Albums</h1>
<% @ar.take(5).each do |album|%>
    <div class="clearfix">
        <div class="column menu">
            <%= link_to (image_tag album[0].image,style:"width:250px; height:250px", class: 'image'), album[0] %>
        </div>
        <div class="column content">
            <div class="right">
                <h1 style="font-size:5vw"><%= link_to (album[0].title), album[0], style: 'color:#000000'%></h1>
                <h1 style="text-align: right"><%= "##{@ar.index(album) + 1}" %></h1>
            </div>
            <h2><%= link_to (album[0].artist), album[0], style: 'color:#000000'%></h2>
            <p style="font-size:2vw" class="glyphicon glyphicon-star-empty"><%= album[1] %></p>
        </div>
    </div>
<%end%>
<h1>Top 5 Worst Albums</h1>
<% @ar.last(5).reverse_each do |album|%>
    <div class="clearfix">
        <div class="column menu">
            <%= link_to (image_tag album[0].image,style:"width:250px; height:250px", class: 'image'), album[0] %>
        </div>
        <div class="column content">
            <div class="right">
                <h1 style="font-size:5vw"><%= link_to (album[0].title), album[0], style: 'color:#000000'%></h1>
                <h1 style="text-align: right"><%= "##{@ar.index(album) + 1}" %></h1>
            </div>
            <h2><%= link_to (album[0].artist), album[0], style: 'color:#000000'%></h2>
            <p style="font-size:2vw" class="glyphicon glyphicon-star-empty"><%= album[1] %></p>
        </div>
    </div>
<%end%>

app/views/albums/worst_ranked.html.erb
<h1 style="color:white"><%= t "top_5_worst_albums"%></h1>
<% @ar.take(5).each do |album|%>
    <div class="clearfix">
        <div class="column menu">
            <%= link_to (image_tag album[0].cover,style:"width:250px; height:250px", class: 'image'), album[0] %>
        </div>
        <div class="column content">
            <div class="right">
                <h1 style="font-size:5vw"><%= link_to (album[0].title), album[0], style: 'color:white'%></h1>
                <h1 style="text-align: right; color:white"><%= "##{@ar.index(album) + 1}" %></h1>
            </div>
            <h2><%= link_to (album[0].artist), singer_path(album[0].singer_id), style: 'color:white'%></h2>
            <p style="font-size:2vw; color:white" class="glyphicon glyphicon-star-empty"><%= album[1] %></p>
        </div>
    </div>
<%end%>