config/routes.rb
Rails.application.routes.draw do
  get 'recommendations/view'
  get 'favourites/view'
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    resources :singers
    get 'search/search', to: 'search#search'
    devise_for :users
    root 'albums#index'
    resources :albums do
      collection do
        get 'search', 'artist', 'top_ranked', 'worst_ranked', 'favourite'
      end
      resources :reviews, except: %i[show index]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[show edit update destroy]
  before_action :set_album
  before_action :authenticate_user!
  # GET /reviews or /reviews.json

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit; end

  # POST /reviews or /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.album_id = @album.id
    respond_to do |format|
      if @review.save
        format.html { redirect_to album_url(@album), notice: (t 'review_create') }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1 or /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to review_url(@review), notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1 or /reviews/1.json
  def destroy
    @review.destroy

    respond_to do |format|
      format.html { redirect_to album_url(@album), notice: (t 'review_destroy') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_review
    @review = Review.find(params[:id])
  end

  def set_album
    @album = Album.find(params[:album_id])
  end

  # Only allow a list of trusted parameters through.
  def review_params
    params.require(:review).permit(:rating, :comment)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for([@album, @review]) do |form| %>
  <% if @review.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% @review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="wrapper">
    <form action="#">
          <div class="h5 font-weight-bold mb-3"><%= form.label :rating,(t "your_mark")%></div>
          <div class="form-group d-flex align-items-center">
            <%= form.number_field :rating, min: 1, max: 10, class: "form-control" %>
          </div>
          <div class="h5 font-weight-bold mb-3"><%= form.label :comment %></div>
        <div class="form-group d-flex align-items-center">
          <%= form.text_area :comment, class: "form-control" %>
        </div>         
          <%= form.submit (t "create_review"), class: "btn btn-primary mb-3"%>                    
    </form>
  </div>
<% end %>

app/views/reviews/_review.html.erb
<div id="<%= dom_id review %>">
  <p>
    <strong>Rating:</strong>
    <%= review.rating %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= review.comment %>
  </p>

  <p>
    <strong>User:</strong>
    <%= review.user.try(:email) %>
  </p>

</div>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render "form", review: @review %>

<br>

<div>
  <%= link_to "Back to reviews", album_path(@album) %>
</div>

app/views/reviews/new.html.erb
<h1 style="color:white;position: relative;left: 35%;"><%= t "new_review" %></h1>

<%= render "form", review: @review %>

<br>

<div>
  <%= link_to (t "bak"), album_path(@album), style: 'color:white'  %>
</div>