config/routes.rb
Rails.application.routes.draw do
  get 'recommendations/view'
  get 'favourites/view'
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    resources :singers
    get 'search/search', to: 'search#search'
    devise_for :users
    root 'albums#index'
    resources :albums do
      collection do
        get 'search', 'artist', 'top_ranked', 'worst_ranked', 'favourite'
      end
      resources :reviews, except: %i[show index]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_header.html.erb
<header>
    <nav class="navbar navbar-light bg-light rotate" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <%= link_to (image_tag "music-logo-png-2343.png", class: "navbar-brand"), root_path %>
            </div>
                <ul class="nav navbar-nav">
                    <% if user_signed_in? %>
                        <% if current_user.admin? %>
                            <li><%= link_to (t "add_album"), new_album_path%></li>
                            <li><%= link_to (t "show_artists"), singers_path %></li>
                            <li><%= link_to (t "add_artist"), new_singer_path %></li>
                            <li><%= link_to (t "account"), edit_user_registration_path %></li>
                            <li><%= link_to (t "favourite"), favourite_albums_path%></li>
                            <li><%= link_to (t "recommendations"), recommendations_view_path%></li>
                            <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown"><%= t "ranked"%></a>
                                <ul class="dropdown-menu">
                                    <li style="color:#337ab7"><%= link_to (t "top_ranked"), top_ranked_albums_path%></li>
                                    <li style="color:#337ab7"><%= link_to (t "worst_ranked"), worst_ranked_albums_path%></li>
                                </ul>
                            </li>
                        <% else %>
                            <li><%= link_to (t "show_artists"), singers_path %></li>
                            <li><%= link_to (t "account"), edit_user_registration_path %></li>
                            <li><%= link_to (t "favourite"), favourite_albums_path%></li>
                            <li><%= link_to (t "recommendations"), recommendations_view_path%></li>
                            <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown"><%= t "ranked"%><span></span></a>
                                <ul class="dropdown-menu">
                                    <li style="color:#337ab7"><%= link_to (t "top_ranked"), top_ranked_albums_path%></li>
                                    <li style="color:#337ab7"><%= link_to (t "worst_ranked"), worst_ranked_albums_path%></li>
                                </ul>
                            </li>
                        <% end %>
                    <% else %>
                        <li><%= link_to (t "sign_up"), new_user_registration_path, class: "active" %></li>
                        <li><%= link_to (t "log_in"), new_user_session_path, class: "active" %></li>
                    <% end %>
                </ul>
                <%= form_tag search_search_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
                    <p>
                        <%= text_field_tag :search, params[:search], class: "form-control" %>
                        <%= submit_tag (t "search"), name: nil, class: "btn btn-default" %>
                    </p>
                <% end %>
        </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style>
    .container-fluid .nav.navbar-nav {
        display: flex;
        color: red; 
        flex-direction: row;
    }
    body{
      background-color:grey;
      font-family: Monospace;
 }

  </style>

  </head>

  <body>
    <%= render "layouts/header" %>

    <div class="container rotate">
      <% flash.each do |name, msg|%>
        <%= content_tag(:div, msg, class: "alert alert-info")%>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>